package characterbuilder.character.spell;

import characterbuilder.character.characterclass.CharacterClass;
import static characterbuilder.character.characterclass.CharacterClass.*;
import static characterbuilder.character.spell.Spell.*;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;

public class SpellClassMap {

    private final Map<Spell, EnumSet<CharacterClass>> map = new HashMap<>();
    private final EnumMap<CharacterClass, CharacterClass> classMap
        = new EnumMap<>(CharacterClass.class);

    public SpellClassMap() {
        map.put(ACID_ARROW, EnumSet.of(WIZARD));
        map.put(ACID_SPLASH, EnumSet.of(SORCERER, WIZARD));
        map.put(AID, EnumSet.of(CLERIC, PALADIN));
        map.put(ALARM, EnumSet.of(RANGER, WIZARD));
        map.put(ALTER_SELF, EnumSet.of(SORCERER, WIZARD));
        map.put(ANIMAL_FRIENDSHIP, EnumSet.of(RANGER, DRUID, BARD));
        map.put(ANIMAL_MESSENGER, EnumSet.of(RANGER, DRUID, BARD));
        map.put(ANIMAL_SHAPES, EnumSet.of(DRUID));
        map.put(ANIMATE_DEAD, EnumSet.of(CLERIC, WIZARD));
        map.put(ANIMATE_OBJECTS, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(ANTILIFE_SHELL, EnumSet.of(DRUID));
        map.put(ANTIMAGIC_FIELD, EnumSet.of(CLERIC, WIZARD));
        map.put(ANTIPATHY_SYMPATHY, EnumSet.of(DRUID, WIZARD));
        map.put(ARCANE_EYE, EnumSet.of(WIZARD));
        map.put(ARCANE_GATE, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(ARCANE_HAND, EnumSet.of(WIZARD));
        map.put(ARCANE_LOCK, EnumSet.of(WIZARD));
        map.put(ARCANE_SWORD, EnumSet.of(BARD, WIZARD));
        map.put(ARCANISTS_MAGIC_AURA, EnumSet.of(WIZARD));
        map.put(ARMOUR_OF_AGATHYS, EnumSet.of(WARLOCK));
        map.put(ARMS_OF_HADAR, EnumSet.of(WARLOCK));
        map.put(ASTRAL_PROJECTION, EnumSet.of(WARLOCK, CLERIC, WIZARD));
        map.put(AUGURY, EnumSet.of(CLERIC));
        map.put(AURA_OF_LIFE, EnumSet.of(PALADIN));
        map.put(AURA_OF_PURITY, EnumSet.of(PALADIN));
        map.put(AURA_OF_VITALITY, EnumSet.of(PALADIN));
        map.put(AWAKEN, EnumSet.of(DRUID, BARD));
        map.put(BANE, EnumSet.of(CLERIC, BARD));
        map.put(BANISHING_SMITE, EnumSet.of(PALADIN));
        map.put(BANISHMENT, EnumSet.of(WARLOCK, CLERIC, PALADIN, SORCERER, WIZARD));
        map.put(BARKSKIN, EnumSet.of(RANGER, DRUID));
        map.put(BEACON_OF_HOPE, EnumSet.of(CLERIC));
        map.put(BEAST_SENSE, EnumSet.of(RANGER, DRUID));
        map.put(BESTOW_CURSE, EnumSet.of(CLERIC, BARD, WIZARD));
        map.put(BLACK_TENTACLES, EnumSet.of(WIZARD));
        map.put(BLADE_BARRIER, EnumSet.of(CLERIC));
        map.put(BLADE_WARD, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(BLESS, EnumSet.of(CLERIC, PALADIN));
        map.put(BLIGHT, EnumSet.of(WARLOCK, DRUID, SORCERER, WIZARD));
        map.put(BLINDING_SMITE, EnumSet.of(PALADIN));
        map.put(BLINDNESS_DEAFNESS, EnumSet.of(CLERIC, SORCERER, BARD, WIZARD));
        map.put(BLINK, EnumSet.of(SORCERER, WIZARD));
        map.put(BLUR, EnumSet.of(SORCERER, WIZARD));
        map.put(BRANDING_SMITE, EnumSet.of(PALADIN));
        map.put(BURNING_HANDS, EnumSet.of(SORCERER, WIZARD));
        map.put(CALL_LIGHTNING, EnumSet.of(DRUID));
        map.put(CALM_EMOTIONS, EnumSet.of(CLERIC, BARD));
        map.put(CHAIN_LIGHTNING, EnumSet.of(SORCERER, WIZARD));
        map.put(CHARM_PERSON, EnumSet.of(WARLOCK, DRUID, SORCERER, BARD, WIZARD));
        map.put(CHILL_TOUCH, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(CHROMATIC_ORB, EnumSet.of(SORCERER, WIZARD));
        map.put(CIRCLE_OF_DEATH, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(CIRCLE_OF_POWER, EnumSet.of(PALADIN));
        map.put(CLAIRVOYANCE, EnumSet.of(CLERIC, SORCERER, BARD, WIZARD));
        map.put(CLONE, EnumSet.of(WIZARD));
        map.put(CLOUDKILL, EnumSet.of(SORCERER, WIZARD));
        map.put(CLOUD_OF_DAGGERS, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(COLOUR_SPRAY, EnumSet.of(SORCERER, WIZARD));
        map.put(COMMAND, EnumSet.of(CLERIC, PALADIN));
        map.put(COMMUNE, EnumSet.of(CLERIC));
        map.put(COMMUNE_WITH_NATURE, EnumSet.of(RANGER, DRUID));
        map.put(COMPELLED_DUEL, EnumSet.of(PALADIN));
        map.put(COMPREHEND_LANGUAGES, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(COMPULSION, EnumSet.of(BARD));
        map.put(CONE_OF_COLD, EnumSet.of(SORCERER, WIZARD));
        map.put(CONFUSION, EnumSet.of(DRUID, SORCERER, BARD, WIZARD));
        map.put(CONJURE_ANIMALS, EnumSet.of(RANGER, DRUID));
        map.put(CONJURE_BARRAGE, EnumSet.of(RANGER));
        map.put(CONJURE_CELESTIAL, EnumSet.of(CLERIC));
        map.put(CONJURE_ELEMENTAL, EnumSet.of(DRUID, WIZARD));
        map.put(CONJURE_FEY, EnumSet.of(WARLOCK, DRUID));
        map.put(CONJURE_MINOR_ELEMENTALS, EnumSet.of(DRUID, WIZARD));
        map.put(CONJURE_VOLLEY, EnumSet.of(RANGER));
        map.put(CONJURE_WOODLAND_BEINGS, EnumSet.of(RANGER, DRUID));
        map.put(CONTACT_OTHER_PLANE, EnumSet.of(WARLOCK, WIZARD));
        map.put(CONTAGION, EnumSet.of(CLERIC, DRUID));
        map.put(CONTINGENCY, EnumSet.of(WIZARD));
        map.put(CONTINUAL_FLAME, EnumSet.of(CLERIC, WIZARD));
        map.put(CONTROL_WATER, EnumSet.of(CLERIC, DRUID, WIZARD));
        map.put(CONTROL_WEATHER, EnumSet.of(CLERIC, DRUID, WIZARD));
        map.put(CORDON_OF_ARROWS, EnumSet.of(RANGER));
        map.put(COUNTERSPELL, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(CREATE_FOOD_AND_WATER, EnumSet.of(CLERIC, PALADIN));
        map.put(CREATE_OR_DESTROY_WATER, EnumSet.of(CLERIC, DRUID));
        map.put(CREATE_UNDEAD, EnumSet.of(WARLOCK, CLERIC, WIZARD));
        map.put(CREATION, EnumSet.of(SORCERER, WIZARD));
        map.put(CROWN_OF_MADNESS, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(CRUSADERS_MANTLE, EnumSet.of(PALADIN));
        map.put(CURE_WOUNDS, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD));
        map.put(DANCING_LIGHTS, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(DARKNESS, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(DARKVISION, EnumSet.of(RANGER, DRUID, SORCERER));
        map.put(DAYLIGHT, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, SORCERER));
        map.put(DEATH_WARD, EnumSet.of(CLERIC, PALADIN));
        map.put(DELAYED_BLAST_FIREBALL, EnumSet.of(SORCERER, WIZARD));
        map.put(DEMIPLANE, EnumSet.of(WARLOCK, WIZARD));
        map.put(DESTRUCTIVE_WAVE, EnumSet.of(PALADIN));
        map.put(DETECT_EVIL_AND_GOOD, EnumSet.of(CLERIC, PALADIN));
        map.put(DETECT_MAGIC, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, SORCERER, BARD, WIZARD));
        map.put(DETECT_POISON_AND_DISEASE, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN));
        map.put(DETECT_THOUGHTS, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(DIMENSION_DOOR, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(DISGUISE_SELF, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(DISINTEGRATE, EnumSet.of(SORCERER, WIZARD));
        map.put(DISPEL_EVIL_AND_GOOD, EnumSet.of(CLERIC, PALADIN));
        map.put(DISPEL_MAGIC, EnumSet.of(WARLOCK, CLERIC, DRUID, PALADIN, SORCERER, BARD, WIZARD));
        map.put(DISSONANT_WHISPERS, EnumSet.of(BARD));
        map.put(DIVINATION, EnumSet.of(CLERIC));
        map.put(DIVINE_FAVOUR, EnumSet.of(PALADIN));
        map.put(DIVINE_WORD, EnumSet.of(CLERIC));
        map.put(DOMINATE_BEAST, EnumSet.of(DRUID, SORCERER));
        map.put(DOMINATE_MONSTER, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(DOMINATE_PERSON, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(DREAM, EnumSet.of(WARLOCK, BARD, WIZARD));
        map.put(DRUIDCRAFT, EnumSet.of(DRUID));
        map.put(EARTHQUAKE, EnumSet.of(CLERIC, DRUID, SORCERER));
        map.put(ELDRITCH_BLAST, EnumSet.of(WARLOCK));
        map.put(ELEMENTAL_WEAPON, EnumSet.of(PALADIN));
        map.put(ENHANCE_ABILITY, EnumSet.of(CLERIC, DRUID, SORCERER, BARD));
        map.put(ENLARGE_REDUCE, EnumSet.of(SORCERER, WIZARD));
        map.put(ENSNARING_STRIKE, EnumSet.of(RANGER));
        map.put(ENTANGLE, EnumSet.of(DRUID));
        map.put(ENTHRALL, EnumSet.of(WARLOCK, BARD));
        map.put(ETHEREALNESS, EnumSet.of(WARLOCK, CLERIC, SORCERER, BARD, WIZARD));
        map.put(EXPEDITIOUS_RETREAT, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(EYEBITE, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(FABRICATE, EnumSet.of(WIZARD));
        map.put(FAERIE_FIRE, EnumSet.of(DRUID, BARD));
        map.put(FAITHFUL_HOUND, EnumSet.of(WIZARD));
        map.put(FALSE_LIFE, EnumSet.of(SORCERER, WIZARD));
        map.put(FEAR, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(FEATHER_FALL, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(FEEBLEMIND, EnumSet.of(WARLOCK, DRUID, BARD, WIZARD));
        map.put(FEIGN_DEATH, EnumSet.of(CLERIC, DRUID, BARD, WIZARD));
        map.put(FIND_FAMILIAR, EnumSet.of(WIZARD));
        map.put(FIND_STEED, EnumSet.of(PALADIN));
        map.put(FIND_THE_PATH, EnumSet.of(CLERIC, DRUID, BARD));
        map.put(FIND_TRAPS, EnumSet.of(RANGER, CLERIC, DRUID));
        map.put(FINGER_OF_DEATH, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(FIREBALL, EnumSet.of(SORCERER, WIZARD));
        map.put(FIRE_BOLT, EnumSet.of(SORCERER, WIZARD));
        map.put(FIRE_SHIELD, EnumSet.of(WIZARD));
        map.put(FIRE_STORM, EnumSet.of(CLERIC, DRUID, SORCERER));
        map.put(FLAME_BLADE, EnumSet.of(DRUID));
        map.put(FLAME_STRIKE, EnumSet.of(CLERIC));
        map.put(FLAMING_SPHERE, EnumSet.of(DRUID, WIZARD));
        map.put(FLESH_TO_STONE, EnumSet.of(WARLOCK, WIZARD));
        map.put(FLOATING_DISK, EnumSet.of(WIZARD));
        map.put(FLY, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(FOG_CLOUD, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        map.put(FORBIDDANCE, EnumSet.of(CLERIC));
        map.put(FORCECAGE, EnumSet.of(WARLOCK, BARD, WIZARD));
        map.put(FORESIGHT, EnumSet.of(WARLOCK, DRUID, BARD, WIZARD));
        map.put(FREEDOM_OF_MOVEMENT, EnumSet.of(RANGER, CLERIC, DRUID, BARD));
        map.put(FREEZING_SPHERE, EnumSet.of(WIZARD));
        map.put(FRIENDS, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(GASEOUS_FORM, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(GATE, EnumSet.of(CLERIC, SORCERER, WIZARD));
        map.put(GEAS, EnumSet.of(CLERIC, DRUID, PALADIN, BARD, WIZARD));
        map.put(GENTLE_REPOSE, EnumSet.of(CLERIC, WIZARD));
        map.put(GIANT_INSECT, EnumSet.of(DRUID));
        map.put(GLIBNESS, EnumSet.of(WARLOCK, BARD));
        map.put(GLOBE_OF_INVULNERABILITY, EnumSet.of(SORCERER, WIZARD));
        map.put(GLYPH_OF_WARDING, EnumSet.of(CLERIC, BARD, WIZARD));
        map.put(GOODBERRY, EnumSet.of(RANGER, DRUID));
        map.put(GRASPING_VINE, EnumSet.of(RANGER, DRUID));
        map.put(GREASE, EnumSet.of(WIZARD));
        map.put(GREATER_INVISIBILITY, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(GREATER_RESTORATION, EnumSet.of(CLERIC, DRUID, BARD));
        map.put(GUARDIAN_OF_FAITH, EnumSet.of(CLERIC));
        map.put(GUARDS_AND_WARDS, EnumSet.of(BARD, WIZARD));
        map.put(GUIDANCE, EnumSet.of(CLERIC, DRUID));
        map.put(GUIDING_BOLT, EnumSet.of(CLERIC));
        map.put(GUST_OF_WIND, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(HAIL_OF_THORNS, EnumSet.of(RANGER));
        map.put(HALLOW, EnumSet.of(CLERIC));
        map.put(HALLUCINATORY_TERRAIN, EnumSet.of(WARLOCK, DRUID, BARD, WIZARD));
        map.put(HARM, EnumSet.of(CLERIC));
        map.put(HASTE, EnumSet.of(SORCERER, WIZARD));
        map.put(HEAL, EnumSet.of(CLERIC, DRUID));
        map.put(HEALING_WORD, EnumSet.of(CLERIC, DRUID, BARD));
        map.put(HEAT_METAL, EnumSet.of(DRUID, BARD));
        map.put(HELLISH_REBUKE, EnumSet.of(WARLOCK));
        map.put(HEROES_FEAST, EnumSet.of(CLERIC, DRUID));
        map.put(HEROISM, EnumSet.of(PALADIN, BARD));
        map.put(HEX, EnumSet.of(WARLOCK));
        map.put(HIDEOUS_LAUGHTER, EnumSet.of(BARD, WIZARD));
        map.put(HOLD_MONSTER, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(HOLD_PERSON, EnumSet.of(WARLOCK, CLERIC, DRUID, SORCERER, BARD, WIZARD));
        map.put(HOLY_AURA, EnumSet.of(CLERIC));
        map.put(HUNGER_OF_HADAR, EnumSet.of(WARLOCK));
        map.put(HUNTERS_MARK, EnumSet.of(RANGER));
        map.put(HYPNOTIC_PATTERN, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(ICE_STORM, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(IDENTIFY, EnumSet.of(BARD, WIZARD));
        map.put(ILLUSORY_SCRIPT, EnumSet.of(WARLOCK, BARD, WIZARD));
        map.put(IMPRISONMENT, EnumSet.of(WARLOCK, WIZARD));
        map.put(INCENDIARY_CLOUD, EnumSet.of(SORCERER, WIZARD));
        map.put(INFLICT_WOUNDS, EnumSet.of(CLERIC));
        map.put(INSECT_PLAGUE, EnumSet.of(CLERIC, DRUID, SORCERER));
        map.put(INSTANT_SUMMONS, EnumSet.of(WIZARD));
        map.put(INVISIBILITY, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(IRRESISTIBLE_DANCE, EnumSet.of(BARD, WIZARD));
        map.put(JUMP, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        map.put(KNOCK, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(LEGEND_LORE, EnumSet.of(CLERIC, BARD, WIZARD));
        map.put(LESSER_RESTORATION, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD));
        map.put(LEVITATE, EnumSet.of(SORCERER, WIZARD));
        map.put(LIGHT, EnumSet.of(CLERIC, SORCERER, BARD, WIZARD));
        map.put(LIGHTNING_ARROW, EnumSet.of(RANGER));
        map.put(LIGHTNING_BOLT, EnumSet.of(SORCERER, WIZARD));
        map.put(LOCATE_ANIMALS_OR_PLANTS, EnumSet.of(RANGER, DRUID, BARD));
        map.put(LOCATE_CREATURE, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD, WIZARD));
        map.put(LOCATE_OBJECT, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD, WIZARD));
        map.put(LONGSTRIDER, EnumSet.of(RANGER, DRUID, BARD, WIZARD));
        map.put(MAGE_ARMOR, EnumSet.of(SORCERER, WIZARD));
        map.put(MAGE_HAND, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(MAGIC_CIRCLE, EnumSet.of(WARLOCK, CLERIC, PALADIN, WIZARD));
        map.put(MAGIC_JAR, EnumSet.of(WIZARD));
        map.put(MAGIC_MISSILE, EnumSet.of(SORCERER, WIZARD));
        map.put(MAGIC_MOUTH, EnumSet.of(BARD, WIZARD));
        map.put(MAGIC_WEAPON, EnumSet.of(PALADIN, WIZARD));
        map.put(MAGNIFICENT_MANSION, EnumSet.of(BARD, WIZARD));
        map.put(MAJOR_IMAGE, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(MASS_CURE_WOUNDS, EnumSet.of(CLERIC, DRUID, BARD));
        map.put(MASS_HEAL, EnumSet.of(CLERIC));
        map.put(MASS_HEALING_WORD, EnumSet.of(CLERIC));
        map.put(MASS_SUGGESTION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(MAZE, EnumSet.of(WIZARD));
        map.put(MELD_INTO_STONE, EnumSet.of(CLERIC, DRUID));
        map.put(MENDING, EnumSet.of(CLERIC, DRUID, SORCERER, BARD, WIZARD));
        map.put(MESSAGE, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(METEOR_SWARM, EnumSet.of(SORCERER, WIZARD));
        map.put(MIND_BLANK, EnumSet.of(BARD, WIZARD));
        map.put(MINOR_ILLUSION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(MIRAGE_ARCANE, EnumSet.of(DRUID, BARD, WIZARD));
        map.put(MIRROR_IMAGE, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(MISLEAD, EnumSet.of(BARD, WIZARD));
        map.put(MISTY_STEP, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(MODIFY_MEMORY, EnumSet.of(BARD, WIZARD));
        map.put(MOONBEAM, EnumSet.of(DRUID));
        map.put(MOVE_EARTH, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(NONDETECTION, EnumSet.of(RANGER, BARD, WIZARD));
        map.put(PASSWALL, EnumSet.of(WIZARD));
        map.put(PASS_WITHOUT_TRACE, EnumSet.of(RANGER, DRUID));
        map.put(PHANTASMAL_FORCE, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(PHANTASMAL_KILLER, EnumSet.of(WIZARD));
        map.put(PHANTOM_STEED, EnumSet.of(WIZARD));
        map.put(PLANAR_ALLY, EnumSet.of(CLERIC));
        map.put(PLANAR_BINDING, EnumSet.of(CLERIC, DRUID, BARD, WIZARD));
        map.put(PLANE_SHIFT, EnumSet.of(WARLOCK, CLERIC, DRUID, SORCERER, WIZARD));
        map.put(PLANT_GROWTH, EnumSet.of(RANGER, DRUID, BARD));
        map.put(POISON_SPRAY, EnumSet.of(WARLOCK, DRUID, SORCERER, WIZARD));
        map.put(POLYMORPH, EnumSet.of(DRUID, SORCERER, BARD, WIZARD));
        map.put(POWER_WORD_HEAL, EnumSet.of(BARD));
        map.put(POWER_WORD_KILL, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(POWER_WORD_STUN, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(PRAYER_OF_HEALING, EnumSet.of(CLERIC));
        map.put(PRESTIDIGITATION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(PRISMATIC_SPRAY, EnumSet.of(SORCERER, WIZARD));
        map.put(PRISMATIC_WALL, EnumSet.of(WIZARD));
        map.put(PRIVATE_SANCTUM, EnumSet.of(WIZARD));
        map.put(PRODUCE_FLAME, EnumSet.of(DRUID));
        map.put(PROGRAMMED_ILLUSION, EnumSet.of(BARD, WIZARD));
        map.put(PROJECT_IMAGE, EnumSet.of(BARD, WIZARD));
        map.put(PROTECTION_FROM_ENERGY, EnumSet.of(RANGER, CLERIC, DRUID, SORCERER, WIZARD));
        map.put(PROTECTION_FROM_EVIL_AND_GOOD, EnumSet.of(WARLOCK, CLERIC, PALADIN, WIZARD));
        map.put(PROTECTION_FROM_POISON, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN));
        map.put(PURIFY_FOOD_AND_DRINK, EnumSet.of(CLERIC, DRUID, PALADIN));
        map.put(RAISE_DEAD, EnumSet.of(CLERIC, PALADIN, BARD));
        map.put(RAY_OF_ENFEEBLEMENT, EnumSet.of(WARLOCK, WIZARD));
        map.put(RAY_OF_FROST, EnumSet.of(SORCERER, WIZARD));
        map.put(RAY_OF_SICKNESS, EnumSet.of(SORCERER, WIZARD));
        map.put(REGENERATE, EnumSet.of(CLERIC, DRUID, BARD));
        map.put(REINCARNATE, EnumSet.of(DRUID));
        map.put(REMOVE_CURSE, EnumSet.of(WARLOCK, CLERIC, PALADIN, WIZARD));
        map.put(RESILIENT_SPHERE, EnumSet.of(WIZARD));
        map.put(RESISTANCE, EnumSet.of(CLERIC, DRUID));
        map.put(RESURRECTION, EnumSet.of(CLERIC, BARD));
        map.put(REVERSE_GRAVITY, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(REVIVIFY, EnumSet.of(CLERIC, PALADIN));
        map.put(ROPE_TRICK, EnumSet.of(WIZARD));
        map.put(SACRED_FLAME, EnumSet.of(CLERIC));
        map.put(SANCTUARY, EnumSet.of(CLERIC));
        map.put(SCORCHING_RAY, EnumSet.of(SORCERER, WIZARD));
        map.put(SCRYING, EnumSet.of(WARLOCK, CLERIC, DRUID, BARD, WIZARD));
        map.put(SEARING_SMITE, EnumSet.of(PALADIN));
        map.put(SECRET_CHEST, EnumSet.of(WIZARD));
        map.put(SEEMING, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(SEE_INVISIBILITY, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(SENDING, EnumSet.of(CLERIC, BARD, WIZARD, WIZARD));
        map.put(SEQUESTER, EnumSet.of(WIZARD));
        map.put(SHAPECHANGE, EnumSet.of(DRUID, WIZARD));
        map.put(SHATTER, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(SHIELD, EnumSet.of(SORCERER, WIZARD));
        map.put(SHIELD_OF_FAITH, EnumSet.of(CLERIC, PALADIN));
        map.put(SHILLELAGH, EnumSet.of(DRUID));
        map.put(SHOCKING_GRASP, EnumSet.of(SORCERER, WIZARD));
        map.put(SILENCE, EnumSet.of(RANGER, CLERIC, BARD));
        map.put(SILENT_IMAGE, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(SIMULACRUM, EnumSet.of(WIZARD));
        map.put(SLEEP, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(SLEET_STORM, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(SLOW, EnumSet.of(SORCERER, WIZARD));
        map.put(SPARE_THE_DYING, EnumSet.of(CLERIC));
        map.put(SPEAK_WITH_ANIMALS, EnumSet.of(RANGER, DRUID, BARD));
        map.put(SPEAK_WITH_DEAD, EnumSet.of(CLERIC, BARD));
        map.put(SPEAK_WITH_PLANTS, EnumSet.of(RANGER, DRUID, BARD));
        map.put(SPIDER_CLIMB, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(SPIKE_GROWTH, EnumSet.of(RANGER, DRUID));
        map.put(SPIRITUAL_WEAPON, EnumSet.of(CLERIC));
        map.put(SPIRIT_GUARDIANS, EnumSet.of(CLERIC));
        map.put(STAGGERING_SMITE, EnumSet.of(PALADIN));
        map.put(STINKING_CLOUD, EnumSet.of(SORCERER, BARD, WIZARD, WIZARD));
        map.put(STONESKIN, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        map.put(STONE_SHAPE, EnumSet.of(CLERIC, DRUID, WIZARD));
        map.put(STORM_OF_VENGEANCE, EnumSet.of(DRUID));
        map.put(SUGGESTION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(SUNBEAM, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(SUNBURST, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(SWIFT_QUIVER, EnumSet.of(RANGER));
        map.put(SYMBOL, EnumSet.of(CLERIC, BARD, WIZARD));
        map.put(TELEKINESIS, EnumSet.of(SORCERER, WIZARD));
        map.put(TELEPATHIC_BOND, EnumSet.of(WIZARD));
        map.put(TELEPATHY, EnumSet.of(WIZARD));
        map.put(TELEPORT, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(TELEPORTATION_CIRCLE, EnumSet.of(SORCERER, BARD, WIZARD));
        map.put(THAUMATURGY, EnumSet.of(CLERIC));
        map.put(THORN_WHIP, EnumSet.of(DRUID));
        map.put(THUNDEROUS_SMITE, EnumSet.of(PALADIN));
        map.put(THUNDERWAVE, EnumSet.of(DRUID, SORCERER, BARD, WIZARD));
        map.put(TIME_STOP, EnumSet.of(SORCERER, WIZARD));
        map.put(TINY_HUT, EnumSet.of(BARD, WIZARD));
        map.put(TONGUES, EnumSet.of(WARLOCK, CLERIC, SORCERER, BARD, WIZARD));
        map.put(TRANSPORT_VIA_PLANTS, EnumSet.of(DRUID));
        map.put(TREE_STRIDE, EnumSet.of(RANGER, DRUID));
        map.put(TRUE_POLYMORPH, EnumSet.of(WARLOCK, BARD, WIZARD));
        map.put(TRUE_RESURRECTION, EnumSet.of(CLERIC, DRUID));
        map.put(TRUE_SEEING, EnumSet.of(WARLOCK, CLERIC, SORCERER, BARD, WIZARD));
        map.put(TRUE_STRIKE, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        map.put(TSUNAMI, EnumSet.of(DRUID));
        map.put(UNSEEN_SERVANT, EnumSet.of(WARLOCK, BARD, WIZARD));
        map.put(VAMPIRIC_TOUCH, EnumSet.of(WARLOCK, WIZARD));
        map.put(VICIOUS_MOCKERY, EnumSet.of(BARD));
        map.put(WALL_OF_FIRE, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(WALL_OF_FORCE, EnumSet.of(WIZARD));
        map.put(WALL_OF_ICE, EnumSet.of(WIZARD));
        map.put(WALL_OF_STONE, EnumSet.of(DRUID, SORCERER, WIZARD));
        map.put(WALL_OF_THORNS, EnumSet.of(DRUID));
        map.put(WARDING_BOND, EnumSet.of(CLERIC));
        map.put(WATER_BREATHING, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        map.put(WATER_WALK, EnumSet.of(RANGER, CLERIC, DRUID, SORCERER));
        map.put(WEB, EnumSet.of(SORCERER, WIZARD));
        map.put(WEIRD, EnumSet.of(WIZARD));
        map.put(WIND_WALK, EnumSet.of(DRUID));
        map.put(WIND_WALL, EnumSet.of(RANGER, DRUID));
        map.put(WISH, EnumSet.of(SORCERER, WIZARD));
        map.put(WITCH_BOLT, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        map.put(WORD_OF_RECALL, EnumSet.of(CLERIC));
        map.put(WRATHFUL_SMITE, EnumSet.of(PALADIN));
        map.put(ZONE_OF_TRUTH, EnumSet.of(CLERIC, PALADIN, BARD));

        classMap.put(ROGUE, WIZARD);
        classMap.put(FIGHTER, WIZARD);
    }

    public Stream<Spell> spellsForClass(CharacterClass characterClass) {
        return map.entrySet().stream()
            .filter(e -> e.getValue()
            .contains(classMap.getOrDefault(characterClass, characterClass)))
            .map(Map.Entry::getKey);
    }

    public Stream<Spell> allSpells() {
        return map.keySet().stream();
    }

}
