package characterbuilder.character.ability;

import static characterbuilder.character.ability.Spell.*;
import characterbuilder.character.attribute.CharacterClass;
import static characterbuilder.character.attribute.CharacterClass.*;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Map;
import java.util.stream.Stream;

public class SpellClassMap {

    private final static EnumMap<Spell, EnumSet<CharacterClass>> MAP = new EnumMap<>(Spell.class);

    static {
        MAP.put(ACID_SPLASH, EnumSet.of(SORCERER, WIZARD));
        MAP.put(AID, EnumSet.of(CLERIC, PALADIN));
        MAP.put(ALARM, EnumSet.of(RANGER, WIZARD));
        MAP.put(ALTER_SELF, EnumSet.of(SORCERER, WIZARD));
        MAP.put(ANIMAL_FRIENDSHIP, EnumSet.of(RANGER, DRUID, BARD));
        MAP.put(ANIMAL_MESSENGER, EnumSet.of(RANGER, DRUID, BARD));
        MAP.put(ANIMAL_SHAPES, EnumSet.of(DRUID));
        MAP.put(ANIMATE_DEAD, EnumSet.of(CLERIC, WIZARD));
        MAP.put(ANIMATE_OBJECTS, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(ANTILIFE_SHELL, EnumSet.of(DRUID));
        MAP.put(ANTIMAGIC_FIELD, EnumSet.of(CLERIC, WIZARD));
        MAP.put(ANTIPATHY_SYMPATHY, EnumSet.of(DRUID, WIZARD));
        MAP.put(ARCANE_EYE, EnumSet.of(WIZARD));
        MAP.put(ARCANE_GATE, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(ARCANE_HAND, EnumSet.of(WIZARD));
        MAP.put(ARCANE_LOCK, EnumSet.of(WIZARD));
        MAP.put(ARCANISTS_MAGIC_AURA, EnumSet.of(WIZARD));
        MAP.put(ARMOUR_OF_AGATHYS, EnumSet.of(WARLOCK));
        MAP.put(ARMS_OF_HADAR, EnumSet.of(WARLOCK));
        MAP.put(ASTRAL_PROJECTION, EnumSet.of(WARLOCK, CLERIC, WIZARD));
        MAP.put(AUGURY, EnumSet.of(CLERIC));
        MAP.put(AURA_OF_LIFE, EnumSet.of(PALADIN));
        MAP.put(AURA_OF_PURITY, EnumSet.of(PALADIN));
        MAP.put(AURA_OF_VITALITY, EnumSet.of(PALADIN));
        MAP.put(AWAKEN, EnumSet.of(DRUID, BARD));
        MAP.put(BANE, EnumSet.of(CLERIC, BARD));
        MAP.put(BANISHING_SMITE, EnumSet.of(PALADIN));
        MAP.put(BANISHMENT, EnumSet.of(WARLOCK, CLERIC, PALADIN, SORCERER, WIZARD));
        MAP.put(BARKSKIN, EnumSet.of(RANGER, DRUID));
        MAP.put(BEACON_OF_HOPE, EnumSet.of(CLERIC));
        MAP.put(BEAST_SENSE, EnumSet.of(RANGER, DRUID));
        MAP.put(BESTOW_CURSE, EnumSet.of(CLERIC, BARD, WIZARD));
        MAP.put(BLADE_BARRIER, EnumSet.of(CLERIC));
        MAP.put(BLADE_WARD, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(BLESS, EnumSet.of(CLERIC, PALADIN));
        MAP.put(BLIGHT, EnumSet.of(WARLOCK, DRUID, SORCERER, WIZARD));
        MAP.put(BLINDING_SMITE, EnumSet.of(PALADIN));
        MAP.put(BLINDNESS_DEAFNESS, EnumSet.of(CLERIC, SORCERER, BARD, WIZARD));
        MAP.put(BLINK, EnumSet.of(SORCERER, WIZARD));
        MAP.put(BLUR, EnumSet.of(SORCERER, WIZARD));
        MAP.put(BRANDING_SMITE, EnumSet.of(PALADIN));
        MAP.put(BURNING_HANDS, EnumSet.of(SORCERER, WIZARD));
        MAP.put(CALL_LIGHTNING, EnumSet.of(DRUID));
        MAP.put(CALM_EMOTIONS, EnumSet.of(CLERIC, BARD));
        MAP.put(CHAIN_LIGHTNING, EnumSet.of(SORCERER, WIZARD));
        MAP.put(CHARM_PERSON, EnumSet.of(WARLOCK, DRUID, SORCERER, BARD, WIZARD));
        MAP.put(CHILL_TOUCH, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(CHROMATIC_ORB, EnumSet.of(SORCERER, WIZARD));
        MAP.put(CIRCLE_OF_DEATH, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(CIRCLE_OF_POWER, EnumSet.of(PALADIN));
        MAP.put(CLAIRVOYANCE, EnumSet.of(CLERIC, SORCERER, BARD, WIZARD));
        MAP.put(CLONE, EnumSet.of(WIZARD));
        MAP.put(CLOUDKILL, EnumSet.of(SORCERER, WIZARD));
        MAP.put(CLOUD_OF_DAGGERS, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(COLOUR_SPRAY, EnumSet.of(SORCERER, WIZARD));
        MAP.put(COMMAND, EnumSet.of(CLERIC, PALADIN));
        MAP.put(COMMUNE, EnumSet.of(CLERIC));
        MAP.put(COMMUNE_WITH_NATURE, EnumSet.of(RANGER, DRUID));
        MAP.put(COMPELLED_DUEL, EnumSet.of(PALADIN));
        MAP.put(COMPREHEND_LANGUAGES, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(COMPULSION, EnumSet.of(BARD));
        MAP.put(CONE_OF_COLD, EnumSet.of(SORCERER, WIZARD));
        MAP.put(CONFUSION, EnumSet.of(DRUID, SORCERER, BARD, WIZARD));
        MAP.put(CONJURE_ANIMALS, EnumSet.of(RANGER, DRUID));
        MAP.put(CONJURE_BARRAGE, EnumSet.of(RANGER));
        MAP.put(CONJURE_CELESTIAL, EnumSet.of(CLERIC));
        MAP.put(CONJURE_ELEMENTAL, EnumSet.of(DRUID, WIZARD));
        MAP.put(CONJURE_FEY, EnumSet.of(WARLOCK, DRUID));
        MAP.put(CONJURE_MINOR_ELEMENTALS, EnumSet.of(DRUID, WIZARD));
        MAP.put(CONJURE_VOLLEY, EnumSet.of(RANGER));
        MAP.put(CONJURE_WOODLAND_BEINGS, EnumSet.of(RANGER, DRUID));
        MAP.put(CONTACT_OTHER_PLANE, EnumSet.of(WARLOCK, WIZARD));
        MAP.put(CONTAGION, EnumSet.of(CLERIC, DRUID));
        MAP.put(CONTINGENCY, EnumSet.of(WIZARD));
        MAP.put(CONTINUAL_FLAME, EnumSet.of(CLERIC, WIZARD));
        MAP.put(CONTROL_WATER, EnumSet.of(CLERIC, DRUID, WIZARD));
        MAP.put(CONTROL_WEATHER, EnumSet.of(CLERIC, DRUID, WIZARD));
        MAP.put(CORDON_OF_ARROWS, EnumSet.of(RANGER));
        MAP.put(COUNTERSPELL, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(CREATE_FOOD_AND_WATER, EnumSet.of(CLERIC, PALADIN));
        MAP.put(CREATE_OR_DESTROY_WATER, EnumSet.of(CLERIC, DRUID));
        MAP.put(CREATE_UNDEAD, EnumSet.of(WARLOCK, CLERIC, WIZARD));
        MAP.put(CREATION, EnumSet.of(SORCERER, WIZARD));
        MAP.put(CROWN_OF_MADNESS, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(CRUSADERS_MANTLE, EnumSet.of(PALADIN));
        MAP.put(CURE_WOUNDS, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD));
        MAP.put(DANCING_LIGHTS, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(DARKNESS, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(DARKVISION, EnumSet.of(RANGER, DRUID, SORCERER));
        MAP.put(DAYLIGHT, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, SORCERER));
        MAP.put(DEATH_WARD, EnumSet.of(CLERIC, PALADIN));
        MAP.put(DELAYED_BLAST_FIREBALL, EnumSet.of(SORCERER, WIZARD));
        MAP.put(DEMIPLANE, EnumSet.of(WARLOCK, WIZARD));
        MAP.put(DESTRUCTIVE_WAVE, EnumSet.of(PALADIN));
        MAP.put(DETECT_EVIL_AND_GOOD, EnumSet.of(CLERIC, PALADIN));
        MAP.put(DETECT_MAGIC, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, SORCERER, BARD, WIZARD));
        MAP.put(DETECT_POISON_AND_DISEASE, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN));
        MAP.put(DETECT_THOUGHTS, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(DIMENSION_DOOR, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(DISGUISE_SELF, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(DISINTEGRATE, EnumSet.of(SORCERER, WIZARD));
        MAP.put(DISPEL_EVIL_AND_GOOD, EnumSet.of(CLERIC, PALADIN));
        MAP.put(DISPEL_MAGIC, EnumSet.of(WARLOCK, CLERIC, DRUID, PALADIN, SORCERER, BARD, WIZARD));
        MAP.put(DISSONANT_WHISPERS, EnumSet.of(BARD));
        MAP.put(DIVINATION, EnumSet.of(CLERIC));
        MAP.put(DIVINE_FAVOUR, EnumSet.of(PALADIN));
        MAP.put(DIVINE_WORD, EnumSet.of(CLERIC));
        MAP.put(DOMINATE_BEAST, EnumSet.of(DRUID, SORCERER));
        MAP.put(DOMINATE_MONSTER, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(DOMINATE_PERSON, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(DRAWMIJS_INSTANT_SUMMONS, EnumSet.of(WIZARD));
        MAP.put(DREAM, EnumSet.of(WARLOCK, BARD, WIZARD));
        MAP.put(DRUIDCRAFT, EnumSet.of(DRUID));
        MAP.put(EARTHQUAKE, EnumSet.of(CLERIC, DRUID, SORCERER));
        MAP.put(ELDRITCH_BLAST, EnumSet.of(WARLOCK));
        MAP.put(ELEMENTAL_WEAPON, EnumSet.of(PALADIN));
        MAP.put(ENHANCE_ABILITY, EnumSet.of(CLERIC, DRUID, SORCERER, BARD));
        MAP.put(ENLARGE_REDUCE, EnumSet.of(SORCERER, WIZARD));
        MAP.put(ENSNARING_STRIKE, EnumSet.of(RANGER));
        MAP.put(ENTANGLE, EnumSet.of(DRUID));
        MAP.put(ENTHRALL, EnumSet.of(WARLOCK, BARD));
        MAP.put(ETHEREALNESS, EnumSet.of(WARLOCK, CLERIC, SORCERER, BARD, WIZARD));
        MAP.put(EVARDS_BLACK_TENTACLES, EnumSet.of(WIZARD));
        MAP.put(EXPEDITIOUS_RETREAT, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(EYEBITE, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(FABRICATE, EnumSet.of(WIZARD));
        MAP.put(FAERIE_FIRE, EnumSet.of(DRUID, BARD));
        MAP.put(FALSE_LIFE, EnumSet.of(SORCERER, WIZARD));
        MAP.put(FEAR, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(FEATHER_FALL, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(FEEBLEMIND, EnumSet.of(WARLOCK, DRUID, BARD, WIZARD));
        MAP.put(FEIGN_DEATH, EnumSet.of(CLERIC, DRUID, BARD, WIZARD));
        MAP.put(FIND_FAMILIAR, EnumSet.of(WIZARD));
        MAP.put(FIND_STEED, EnumSet.of(PALADIN));
        MAP.put(FIND_THE_PATH, EnumSet.of(CLERIC, DRUID, BARD));
        MAP.put(FIND_TRAPS, EnumSet.of(RANGER, CLERIC, DRUID));
        MAP.put(FINGER_OF_DEATH, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(FIREBALL, EnumSet.of(SORCERER, WIZARD));
        MAP.put(FIRE_BOLT, EnumSet.of(SORCERER, WIZARD));
        MAP.put(FIRE_SHIELD, EnumSet.of(WIZARD));
        MAP.put(FIRE_STORM, EnumSet.of(CLERIC, DRUID, SORCERER));
        MAP.put(FLAME_BLADE, EnumSet.of(DRUID));
        MAP.put(FLAME_STRIKE, EnumSet.of(CLERIC));
        MAP.put(FLAMING_SPHERE, EnumSet.of(DRUID, WIZARD));
        MAP.put(FLESH_TO_STONE, EnumSet.of(WARLOCK, WIZARD));
        MAP.put(FLY, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(FOG_CLOUD, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        MAP.put(FORBIDDANCE, EnumSet.of(CLERIC));
        MAP.put(FORCECAGE, EnumSet.of(WARLOCK, BARD, WIZARD));
        MAP.put(FORESIGHT, EnumSet.of(WARLOCK, DRUID, BARD, WIZARD));
        MAP.put(FREEDOM_OF_MOVEMENT, EnumSet.of(RANGER, CLERIC, DRUID, BARD));
        MAP.put(FREEZING_SPHERE, EnumSet.of(WIZARD));
        MAP.put(FRIENDS, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(GASEOUS_FORM, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(GATE, EnumSet.of(CLERIC, SORCERER, WIZARD));
        MAP.put(GEAS, EnumSet.of(CLERIC, DRUID, PALADIN, BARD, WIZARD));
        MAP.put(GENTLE_REPOSE, EnumSet.of(CLERIC, WIZARD));
        MAP.put(GIANT_INSECT, EnumSet.of(DRUID));
        MAP.put(GLIBNESS, EnumSet.of(WARLOCK, BARD));
        MAP.put(GLOBE_OF_INVULNERABILITY, EnumSet.of(SORCERER, WIZARD));
        MAP.put(GLYPH_OF_WARDING, EnumSet.of(CLERIC, BARD, WIZARD));
        MAP.put(GOODBERRY, EnumSet.of(RANGER, DRUID));
        MAP.put(GRASPING_VINE, EnumSet.of(RANGER, DRUID));
        MAP.put(GREASE, EnumSet.of(WIZARD));
        MAP.put(GREATER_INVISIBILITY, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(GREATER_RESTORATION, EnumSet.of(CLERIC, DRUID, BARD));
        MAP.put(GUARDIAN_OF_FAITH, EnumSet.of(CLERIC));
        MAP.put(GUARDS_AND_WARDS, EnumSet.of(BARD, WIZARD));
        MAP.put(GUIDANCE, EnumSet.of(CLERIC, DRUID));
        MAP.put(GUIDING_BOLT, EnumSet.of(CLERIC));
        MAP.put(GUST_OF_WIND, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(HAIL_OF_THORNS, EnumSet.of(RANGER));
        MAP.put(HALLOW, EnumSet.of(CLERIC));
        MAP.put(HALLUCINATORY_TERRAIN, EnumSet.of(WARLOCK, DRUID, BARD, WIZARD));
        MAP.put(HARM, EnumSet.of(CLERIC));
        MAP.put(HASTE, EnumSet.of(SORCERER, WIZARD));
        MAP.put(HEAL, EnumSet.of(CLERIC, DRUID));
        MAP.put(HEALING_WORD, EnumSet.of(CLERIC, DRUID, BARD));
        MAP.put(HEAT_METAL, EnumSet.of(DRUID, BARD));
        MAP.put(HELLISH_REBUKE, EnumSet.of(WARLOCK));
        MAP.put(HEROES_FEAST, EnumSet.of(CLERIC, DRUID));
        MAP.put(HEROISM, EnumSet.of(PALADIN, BARD));
        MAP.put(HEX, EnumSet.of(WARLOCK));
        MAP.put(HOLD_MONSTER, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(HOLD_PERSON, EnumSet.of(WARLOCK, CLERIC, DRUID, SORCERER, BARD, WIZARD));
        MAP.put(HOLY_AURA, EnumSet.of(CLERIC));
        MAP.put(HUNGER_OF_HADAR, EnumSet.of(WARLOCK));
        MAP.put(HUNTERS_MARK, EnumSet.of(RANGER));
        MAP.put(HYPNOTIC_PATTERN, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(ICE_STORM, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(IDENTIFY, EnumSet.of(BARD, WIZARD));
        MAP.put(ILLUSORY_SCRIPT, EnumSet.of(WARLOCK, BARD, WIZARD));
        MAP.put(IMPRISONMENT, EnumSet.of(WARLOCK, WIZARD));
        MAP.put(INCENDIARY_CLOUD, EnumSet.of(SORCERER, WIZARD));
        MAP.put(INFLICT_WOUNDS, EnumSet.of(CLERIC));
        MAP.put(INSECT_PLAGUE, EnumSet.of(CLERIC, DRUID, SORCERER));
        MAP.put(INVISIBILITY, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(IRRESISTIBLE_DANCE, EnumSet.of(BARD, WIZARD));
        MAP.put(JUMP, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        MAP.put(KNOCK, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(LEGEND_LORE, EnumSet.of(CLERIC, BARD, WIZARD));
        MAP.put(LEOMUNDS_SECRET_CHEST, EnumSet.of(WIZARD));
        MAP.put(LESSER_RESTORATION, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD));
        MAP.put(LEVITATE, EnumSet.of(SORCERER, WIZARD));
        MAP.put(LIGHT, EnumSet.of(CLERIC, SORCERER, BARD, WIZARD));
        MAP.put(LIGHTNING_ARROW, EnumSet.of(RANGER));
        MAP.put(LIGHTNING_BOLT, EnumSet.of(SORCERER, WIZARD));
        MAP.put(LOCATE_ANIMALS_OR_PLANTS, EnumSet.of(RANGER, DRUID, BARD));
        MAP.put(LOCATE_CREATURE, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD, WIZARD));
        MAP.put(LOCATE_OBJECT, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN, BARD, WIZARD));
        MAP.put(LONGSTRIDER, EnumSet.of(RANGER, DRUID, BARD, WIZARD));
        MAP.put(MAGE_ARMOR, EnumSet.of(SORCERER, WIZARD));
        MAP.put(MAGE_HAND, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(MAGIC_CIRCLE, EnumSet.of(WARLOCK, CLERIC, PALADIN, WIZARD));
        MAP.put(MAGIC_JAR, EnumSet.of(WIZARD));
        MAP.put(MAGIC_MISSILE, EnumSet.of(SORCERER, WIZARD));
        MAP.put(MAGIC_MOUTH, EnumSet.of(BARD, WIZARD));
        MAP.put(MAGIC_WEAPON, EnumSet.of(PALADIN, WIZARD));
        MAP.put(MAGNIFICENT_MANSION, EnumSet.of(BARD, WIZARD));
        MAP.put(MAJOR_IMAGE, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(MASS_CURE_WOUNDS, EnumSet.of(CLERIC, DRUID, BARD));
        MAP.put(MASS_HEAL, EnumSet.of(CLERIC));
        MAP.put(MASS_HEALING_WORD, EnumSet.of(CLERIC));
        MAP.put(MASS_SUGGESTION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(MAZE, EnumSet.of(WIZARD));
        MAP.put(MELD_INTO_STONE, EnumSet.of(CLERIC, DRUID));
        MAP.put(MELFS_ACID_ARROW, EnumSet.of(WIZARD));
        MAP.put(MENDING, EnumSet.of(CLERIC, DRUID, SORCERER, BARD, WIZARD));
        MAP.put(MESSAGE, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(METEOR_SWARM, EnumSet.of(SORCERER, WIZARD));
        MAP.put(MIND_BLANK, EnumSet.of(BARD, WIZARD));
        MAP.put(MINOR_ILLUSION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(MIRAGE_ARCANE, EnumSet.of(DRUID, BARD, WIZARD));
        MAP.put(MIRROR_IMAGE, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(MISLEAD, EnumSet.of(BARD, WIZARD));
        MAP.put(MISTY_STEP, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(MODIFY_MEMORY, EnumSet.of(BARD, WIZARD));
        MAP.put(MOONBEAM, EnumSet.of(DRUID));
        MAP.put(MORDENKAINENS_FAITHFUL_HOUND, EnumSet.of(WIZARD));
        MAP.put(MORDENKAINENS_PRIVATE_SANCTUM, EnumSet.of(WIZARD));
        MAP.put(MORDENKAINENS_SWORD, EnumSet.of(BARD, WIZARD));
        MAP.put(MOVE_EARTH, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(NONDETECTION, EnumSet.of(RANGER, BARD, WIZARD));
        MAP.put(PASSWALL, EnumSet.of(WIZARD));
        MAP.put(PASS_WITHOUT_TRACE, EnumSet.of(RANGER, DRUID));
        MAP.put(PHANTASMAL_FORCE, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(PHANTASMAL_KILLER, EnumSet.of(WIZARD));
        MAP.put(PHANTOM_STEED, EnumSet.of(WIZARD));
        MAP.put(PLANAR_ALLY, EnumSet.of(CLERIC));
        MAP.put(PLANAR_BINDING, EnumSet.of(CLERIC, DRUID, BARD, WIZARD));
        MAP.put(PLANE_SHIFT, EnumSet.of(WARLOCK, CLERIC, DRUID, SORCERER, WIZARD));
        MAP.put(PLANT_GROWTH, EnumSet.of(RANGER, DRUID, BARD));
        MAP.put(POISON_SPRAY, EnumSet.of(WARLOCK, DRUID, SORCERER, WIZARD));
        MAP.put(POLYMORPH, EnumSet.of(DRUID, SORCERER, BARD, WIZARD));
        MAP.put(POWER_WORD_HEAL, EnumSet.of(BARD));
        MAP.put(POWER_WORD_KILL, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(POWER_WORD_STUN, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(PRAYER_OF_HEALING, EnumSet.of(CLERIC));
        MAP.put(PRESTIDIGITATION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(PRISMATIC_SPRAY, EnumSet.of(SORCERER, WIZARD));
        MAP.put(PRISMATIC_WALL, EnumSet.of(WIZARD));
        MAP.put(PRODUCE_FLAME, EnumSet.of(DRUID));
        MAP.put(PROGRAMMED_ILLUSION, EnumSet.of(BARD, WIZARD));
        MAP.put(PROJECT_IMAGE, EnumSet.of(BARD, WIZARD));
        MAP.put(PROTECTION_FROM_ENERGY, EnumSet.of(RANGER, CLERIC, DRUID, SORCERER, WIZARD));
        MAP.put(PROTECTION_FROM_EVIL_AND_GOOD, EnumSet.of(WARLOCK, CLERIC, PALADIN, WIZARD));
        MAP.put(PROTECTION_FROM_POISON, EnumSet.of(RANGER, CLERIC, DRUID, PALADIN));
        MAP.put(PURIFY_FOOD_AND_DRINK, EnumSet.of(CLERIC, DRUID, PALADIN));
        MAP.put(RAISE_DEAD, EnumSet.of(CLERIC, PALADIN, BARD));
        MAP.put(RARYS_TELEPATHIC_BOND, EnumSet.of(WIZARD));
        MAP.put(RAY_OF_ENFEEBLEMENT, EnumSet.of(WARLOCK, WIZARD));
        MAP.put(RAY_OF_FROST, EnumSet.of(SORCERER, WIZARD));
        MAP.put(RAY_OF_SICKNESS, EnumSet.of(SORCERER, WIZARD));
        MAP.put(REGENERATE, EnumSet.of(CLERIC, DRUID, BARD));
        MAP.put(REINCARNATE, EnumSet.of(DRUID));
        MAP.put(REMOVE_CURSE, EnumSet.of(WARLOCK, CLERIC, PALADIN, WIZARD));
        MAP.put(RESISTANCE, EnumSet.of(CLERIC, DRUID));
        MAP.put(RESURRECTION, EnumSet.of(CLERIC, BARD));
        MAP.put(REVERSE_GRAVITY, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(REVIVIFY, EnumSet.of(CLERIC, PALADIN));
        MAP.put(ROPE_TRICK, EnumSet.of(WIZARD));
        MAP.put(SACRED_FLAME, EnumSet.of(CLERIC));
        MAP.put(SANCTUARY, EnumSet.of(CLERIC));
        MAP.put(SCORCHING_RAY, EnumSet.of(SORCERER, WIZARD));
        MAP.put(SCRYING, EnumSet.of(WARLOCK, CLERIC, DRUID, BARD, WIZARD));
        MAP.put(SEARING_SMITE, EnumSet.of(PALADIN));
        MAP.put(SEEMING, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(SEE_INVISIBILITY, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(SENDING, EnumSet.of(CLERIC, BARD, WIZARD, WIZARD));
        MAP.put(SEQUESTER, EnumSet.of(WIZARD));
        MAP.put(SHAPECHANGE, EnumSet.of(DRUID, WIZARD));
        MAP.put(SHATTER, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(SHIELD, EnumSet.of(SORCERER, WIZARD));
        MAP.put(SHIELD_OF_FAITH, EnumSet.of(CLERIC, PALADIN));
        MAP.put(SHILLELAGH, EnumSet.of(DRUID));
        MAP.put(SHOCKING_GRASP, EnumSet.of(SORCERER, WIZARD));
        MAP.put(SILENCE, EnumSet.of(RANGER, CLERIC, BARD));
        MAP.put(SILENT_IMAGE, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(SIMULACRUM, EnumSet.of(WIZARD));
        MAP.put(SLEEP, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(SLEET_STORM, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(SLOW, EnumSet.of(SORCERER, WIZARD));
        MAP.put(SPARE_THE_DYING, EnumSet.of(CLERIC));
        MAP.put(SPEAK_WITH_ANIMALS, EnumSet.of(RANGER, DRUID, BARD));
        MAP.put(SPEAK_WITH_DEAD, EnumSet.of(CLERIC, BARD));
        MAP.put(SPEAK_WITH_PLANTS, EnumSet.of(RANGER, DRUID, BARD));
        MAP.put(SPIDER_CLIMB, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(SPIKE_GROWTH, EnumSet.of(RANGER, DRUID));
        MAP.put(SPIRITUAL_WEAPON, EnumSet.of(CLERIC));
        MAP.put(SPIRIT_GUARDIANS, EnumSet.of(CLERIC));
        MAP.put(STAGGERING_SMITE, EnumSet.of(PALADIN));
        MAP.put(STINKING_CLOUD, EnumSet.of(SORCERER, BARD, WIZARD, WIZARD));
        MAP.put(STONESKIN, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        MAP.put(STONE_SHAPE, EnumSet.of(CLERIC, DRUID, WIZARD));
        MAP.put(STORM_OF_VENGEANCE, EnumSet.of(DRUID));
        MAP.put(SUGGESTION, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(SUNBEAM, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(SUNBURST, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(SWIFT_QUIVER, EnumSet.of(RANGER));
        MAP.put(SYMBOL, EnumSet.of(CLERIC, BARD, WIZARD));
        MAP.put(TASHAS_HIDEOUS_LAGHTER, EnumSet.of(BARD, WIZARD));
        MAP.put(TELEKINESIS, EnumSet.of(SORCERER, WIZARD));
        MAP.put(TELEPATHY, EnumSet.of(WIZARD));
        MAP.put(TELEPORT, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(TELEPORTATION_CIRCLE, EnumSet.of(SORCERER, BARD, WIZARD));
        MAP.put(TENSERS_FLOATING_DISK, EnumSet.of(WIZARD));
        MAP.put(THAUMATURGY, EnumSet.of(CLERIC));
        MAP.put(THORN_WHIP, EnumSet.of(DRUID));
        MAP.put(THUNDEROUS_SMITE, EnumSet.of(PALADIN));
        MAP.put(THUNDERWAVE, EnumSet.of(DRUID, SORCERER, BARD, WIZARD));
        MAP.put(TIME_STOP, EnumSet.of(SORCERER, WIZARD));
        MAP.put(TINY_HUT, EnumSet.of(BARD, WIZARD));
        MAP.put(TONGUES, EnumSet.of(WARLOCK, CLERIC, SORCERER, BARD, WIZARD));
        MAP.put(TRANSPORT_VIA_PLANTS, EnumSet.of(DRUID));
        MAP.put(TREE_STRIDE, EnumSet.of(RANGER, DRUID));
        MAP.put(TRUE_POLYMORPH, EnumSet.of(WARLOCK, BARD, WIZARD));
        MAP.put(TRUE_RESURRECTION, EnumSet.of(CLERIC, DRUID));
        MAP.put(TRUE_SEEING, EnumSet.of(WARLOCK, CLERIC, SORCERER, BARD, WIZARD));
        MAP.put(TRUE_STRIKE, EnumSet.of(WARLOCK, SORCERER, BARD, WIZARD));
        MAP.put(TSUNAMI, EnumSet.of(DRUID));
        MAP.put(UNSEEN_SERVANT, EnumSet.of(WARLOCK, BARD, WIZARD));
        MAP.put(VAMPIRIC_TOUCH, EnumSet.of(WARLOCK, WIZARD));
        MAP.put(VICIOUS_MOCKERY, EnumSet.of(BARD));
        MAP.put(WALL_OF_FIRE, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(WALL_OF_FORCE, EnumSet.of(WIZARD));
        MAP.put(WALL_OF_ICE, EnumSet.of(WIZARD));
        MAP.put(WALL_OF_STONE, EnumSet.of(DRUID, SORCERER, WIZARD));
        MAP.put(WALL_OF_THORNS, EnumSet.of(DRUID));
        MAP.put(WARDING_BOND, EnumSet.of(CLERIC));
        MAP.put(WATER_BREATHING, EnumSet.of(RANGER, DRUID, SORCERER, WIZARD));
        MAP.put(WATER_WALK, EnumSet.of(RANGER, CLERIC, DRUID, SORCERER));
        MAP.put(WEB, EnumSet.of(SORCERER, WIZARD));
        MAP.put(WEIRD, EnumSet.of(WIZARD));
        MAP.put(WIND_WALK, EnumSet.of(DRUID));
        MAP.put(WIND_WALL, EnumSet.of(RANGER, DRUID));
        MAP.put(WISH, EnumSet.of(SORCERER, WIZARD));
        MAP.put(WITCH_BOLT, EnumSet.of(WARLOCK, SORCERER, WIZARD));
        MAP.put(WORD_OF_RECALL, EnumSet.of(CLERIC));
        MAP.put(WRATHFUL_SMITE, EnumSet.of(PALADIN));
        MAP.put(ZONE_OF_TRUTH, EnumSet.of(CLERIC, PALADIN, BARD));
    }

    private SpellClassMap() {
    }

    public static Stream<Spell> spellsForClass(CharacterClass characterClass) {
        return MAP.entrySet().stream()
            .filter(e -> e.getValue().contains(characterClass))
            .map(Map.Entry::getKey);
    }

}
