package characterbuilder.character.ability;

import characterbuilder.character.Character;
import static characterbuilder.character.ability.MagicSchool.*;
import characterbuilder.character.attribute.Attribute;
import characterbuilder.character.attribute.AttributeType;
import characterbuilder.character.attribute.CharacterClass;
import characterbuilder.utils.StringUtils;
import java.util.stream.Stream;
import org.w3c.dom.Node;

public enum Spell implements Attribute {
    ACID_SPLASH(CONJURATION, 0, "1 action", "60'", "1-2 creatures", "V,S", "-",
        "[max($level 1:1d6,5:2d6,11:3d6, 17:4d6)] acid damage (Dex. save)"),
    AID(ABJURATION, 2, "1 action", "30'", "1-3 creatures", "V,S,M", "8 hours",
        "+5 temporary HP / lev"),
    ALARM(ABJURATION, 1, "1 minute", "30'", "20' cube", "V,S,M", "8 hours",
        "Mental or audible alarm if creature touches or enters area."),
    ALTER_SELF(TRANSMUTATION, 2, "1 action", "self", "-", "V,S", "up to 1 hour",
        "Assume a different physical form."),
    ANIMAL_FRIENDSHIP(ENCHANTMENT, 1, "1 action", "30'", "1 beast", "V,S,M", "24 hours",
        "Charm a beast with Int. under 4. Wis. save. +1 beast / lev"),
    ANIMAL_MESSENGER(ENCHANTMENT, 2, "1 action", "30'", "1 tiny beast", "V,S,M", "24 hours",
        "Beast delivers message. +24 hours / lev"),
    ANIMAL_SHAPES(TRANSMUTATION, 8, "1 action", "30'", "All willing creatures", "V,S",
        "up to 24 hours", "Targets assume form of beast"),
    ANIMATE_DEAD(NECROMANCY, 3, "1 minute", "10'", "1 pile of bones or corpse", "V,S,M", "-",
        "Create and control skeleton or zombie. +2 undead creatures / lev."),
    ANIMATE_OBJECTS(TRANSMUTATION, 5, "1 action", "120'", "up to 10 objects", "V,S",
        "up to 1 minute", "Animate and control objects. +2 objects / lev."),
    ANTILIFE_SHELL(ABJURATION, 5, "1 action", "self", "10' radius", "V,S", "up to 1 hour",
        "Prevents living creatures from entering."),
    ANTIMAGIC_FIELD(ABJURATION, 8, "1 action", "self", "10' radius", "V,S,M", "up to 1 hour",
        "Prevents magic from entering."),
    ANTIPATHY_SYMPATHY(8),
    ARCANE_EYE(MagicSchool.DIVINATION, 4, "1 action", "30'", "-", "V,S,M", "up to 1 hour",
        "remote seeing"),
    ARCANE_GATE(6),
    ARCANE_LOCK(ABJURATION, 2, "1 action", "touch", "1 object", "V,S,M (25gp)", "permanent", "lock"),
    ARMOUR_OF_AGATHYS(1),
    ARMS_OF_HADAR(1),
    ASTRAL_PROJECTION(NECROMANCY, 9, "1 hour", "10'", "1-9 creatures", "VSM (1100gp / cr)", "special",
        "travel to Astral plane"),
    AUGURY(MagicSchool.DIVINATION, 2, "1 minute", "0", "self", "V,S,M (25gp)", "-",
        "receive omen"),
    AURA_OF_LIFE(4),
    AURA_OF_PURITY(4),
    AURA_OF_VITALITY(3),
    AWAKEN(5),
    BANE(1),
    BANISHING_SMITE(5),
    BANISHMENT(4),
    BARKSKIN(2),
    BEACON_OF_HOPE(ABJURATION, 3, "1 action", "30'", "all creatures in range", "V,S",
        "up to 1 minute", "advantage on save vs Wis & Death; max hp healing"),
    BEAST_SENSE(MagicSchool.DIVINATION, 2, "1 action", "touch", "1 beast", "S", "up to 1 hour",
        "see and hear through beast's eyes and ears."),
    BESTOW_CURSE(3),
    BIGBYS_HAND(5),
    BLADE_BARRIER(EVOCATION, 6, "1 action", "90'", "100' long or 60' diameter x20'x5'", "V,S", "up to 10 minutes",
        "6d6 damage (save vs Dex)"),
    BLADE_WARD(0),
    BLESS(ENCHANTMENT, 1, "1 action", "30'", "1-3 (+1 / lev) creatures", "V,S,M", "up to 1 minute",
        "+1d4 to hit / saves"),
    BLIGHT(4),
    BLINDING_SMITE(3),
    BLINDNESS_DEAFNESS(2),
    BLINK(3),
    BLUR(ILLUSION, 2, "1 action", "self", "-", "V", "up to 1 minute",
        "attackers disadvantaged"),
    BRANDING_SMITE(2),
    BURNING_HANDS(EVOCATION, 1, "1 action", "self", "15' cone", "V,S", "-",
        "3d6 (+1d6 / lev) dam"),
    CALL_LIGHTNING(3),
    CALM_EMOTIONS(2),
    CHAIN_LIGHTNING(EVOCATION, 6, "1 action", "150'", "1-4 creatures (+1 / lev) within 30'",
        "V,S,M", "-", "10d8 dam (save vs Dex for half)"),
    CHARM_PERSON(ENCHANTMENT, 1, "1 action", "30'", "1 creature / level", "V,S", "1h",
        "save vs Wis or charmed"),
    CHILL_TOUCH(0),
    CHROMATIC_ORB(1),
    CIRCLE_OF_DEATH(6),
    CIRCLE_OF_POWER(5),
    CLAIRVOYANCE(3),
    CLONE(8),
    CLOUD_OF_DAGGERS(2),
    CLOUDKILL(5),
    COLOUR_SPRAY(1),
    COMMAND(ENCHANTMENT, 1, "1 action", "60'", "1 creature / lev", "V", "1 round",
        "save vs Wis or obey command"),
    COMMUNE(MagicSchool.DIVINATION, 5, "1 minute", "self", "-", "V,S,M", "1 minute",
        "answer 1-3 yes/no questions"),
    COMMUNE_WITH_NATURE(MagicSchool.DIVINATION, 5, "1 minute", "self", "-", "V,S", "-",
        "gain knowledge of up to three facts about surroundings."),
    COMPELLED_DUEL(1),
    COMPREHEND_LANGUAGES(MagicSchool.DIVINATION, 1, "1 action", "self", "-", "V,S,M", "1 hour",
        "understand languages"),
    COMPULSION(4),
    CONE_OF_COLD(EVOCATION, 5, "1 action", "self", "60' cone", "V,S,M", "-",
        "8d8 dam (+1d / lev) (save vs Con 1/2 dam)"),
    CONFUSION(ENCHANTMENT, 4, "1 action", "90'", "all creature in 10' sphere", "V,S,M",
        "up to 1 minute", "Wis. save or random behaviour 1d10 "
        + "(1:random move, 2-6:no action, 7-8:random attack, 9-10: act normall)"),
    CONJURE_ANIMALS(3),
    CONJURE_BARRAGE(3),
    CONJURE_CELESTIAL(7),
    CONJURE_ELEMENTAL(5),
    CONJURE_FEY(6),
    CONJURE_MINOR_ELEMENTALS(4),
    CONJURE_VOLLEY(5),
    CONJURE_WOODLAND_BEINGS(4),
    CONTACT_OTHER_PLANE(5),
    CONTAGION(5),
    CONTINGENCY(6),
    CONTINUAL_FLAME(2),
    CONTROL_WATER(4),
    CONTROL_WEATHER(8),
    CORDON_OF_ARROWS(2),
    COUNTERSPELL(ABJURATION, 3, "1 reaction", "60'", "1 creature", "S", "-",
        "interrupt spell casting; automatic for spells to level three, "
        + "otherwise DC 10 + spell level"),
    CREATE_FOOD_AND_WATER(3),
    CREATE_OR_DESTROY_WATER(1),
    CREATE_UNDEAD(6),
    CREATION(5),
    CROWN_OF_MADNESS(2),
    CRUSADERS_MANTLE(3),
    CURE_WOUNDS(1),
    DANCING_LIGHTS(EVOCATION, 0, "1 action", "120'", "-", "V,S,M", "up to 1 minute",
        "1-4 lights"),
    DARKNESS(2),
    DARKVISION(TRANSMUTATION, 2, "1 action", "touch", "1 creature", "V,S,M", "8 hours",
        "see in dim light to a range of 60'."),
    DAYLIGHT(3),
    DEATH_WARD(4),
    DELAYED_BLAST_FIREBALL(7),
    DEMIPLANE(8),
    DESTRUCTIVE_WAVE(5),
    DETECT_EVIL_AND_GOOD(1),
    DETECT_MAGIC(MagicSchool.DIVINATION, 1, "1 action", "self", "30'", "V,S", "up to 10 minutes",
        "sense magic"),
    DETECT_POISON_AND_DISEASE(1),
    DETECT_THOUGHTS(2),
    DIMENSION_DOOR(CONJURATION, 4, "1 action", "500'", "2 creatures", "V", "-",
        "teleport"),
    DISGUISE_SELF(1),
    DISINTEGRATE(6),
    DISPEL_EVIL_AND_GOOD(5),
    DISPEL_MAGIC(3),
    DISSONANT_WHISPERS(1),
    DIVINATION(MagicSchool.DIVINATION, 4, "1 action", "self", "-", "V,S,M (25gp)", "-",
        "answer 1 question"),
    DIVINE_FAVOUR(1),
    DIVINE_WORD(7),
    DOMINATE_BEAST(4),
    DOMINATE_MONSTER(ENCHANTMENT, 8, "1 action", "60'", "1 creature", "V,S", "up to 1 hour",
        "control, save vs Wis"),
    DOMINATE_PERSON(ENCHANTMENT, 5, "1 action", "60'", "1 creature", "V,S", "up to 1 minute",
        "control, save vs Wis"),
    DRAWMIJS_INSTANT_SUMMONS(6),
    DREAM(ILLUSION, 5, "1 minute", "special", "1 creature", "V,S,M", "8 hours",
        "message in dream, optional 3d6 psychic dam"),
    DRUIDCRAFT(0),
    EARTHQUAKE(EVOCATION, 8, "1 action", "500'", "100' radius", "V,S,M", "up to 1 minute",
        "special"),
    ELDRITCH_BLAST(0),
    ELEMENTAL_WEAPON(3),
    ENHANCE_ABILITY(2),
    ENLARGE_REDUCE(2),
    ENSNARING_STRIKE(1),
    ENTANGLE(1),
    ENTHRALL(2),
    ETHEREALNESS(TRANSMUTATION, 7, "1 action", "self", "1 creature + 3 / lev", "V,S",
        "up to 8 hours", "enter ethereal plane"),
    EVARDS_BLACK_TENTACLES(4),
    EXPEDITIOUS_RETREAT(1),
    EYEBITE(6),
    FABRICATE(4),
    FAERIE_FIRE(EVOCATION, 1, "1 action", "60'", "20' cube", "V", "up to 1 minute",
        "outline in light; Dex. save or attacks advantaged"),
    FALSE_LIFE(1),
    FEAR(3),
    FEATHER_FALL(1),
    FEEBLEMIND(8),
    FEIGN_DEATH(3),
    FIND_FAMILIAR(1),
    FIND_STEED(2),
    FIND_THE_PATH(6),
    FIND_TRAPS(2),
    FINGER_OF_DEATH(7),
    FIREBALL(3),
    FIRE_BOLT(EVOCATION, 0, "1 action", "120'", "1 creature or object", "V,S", "-",
        "ranged attack [($level+7)/6]d10 dam"),
    FIRE_SHIELD(4),
    FIRE_STORM(7),
    FLAME_BLADE(2),
    FLAME_STRIKE(5),
    FLAMING_SPHERE(2),
    FLESH_TO_STONE(6),
    FLY(3),
    FOG_CLOUD(1),
    FORBIDDANCE(6),
    FORCECAGE(7),
    FORESIGHT(9),
    FREEDOM_OF_MOVEMENT(4),
    FRIENDS(0),
    GASEOUS_FORM(TRANSMUTATION, 3, "1 action", "touch", "1 creature", "V,S,M", "up to 1 hour",
        "transform to misty cloud."),
    GATE(9),
    GEAS(5),
    GENTLE_REPOSE(2),
    GIANT_INSECT(4),
    GLIBNESS(8),
    GLOBE_OF_INVULNERABILITY(6),
    GLYPH_OF_WARDING(3),
    GOODBERRY(1),
    GRASPING_VINE(4),
    GREASE(1),
    GREATER_INVISIBILITY(4),
    GREATER_RESTORATION(5),
    GUARDIAN_OF_FAITH(4),
    GUARDS_AND_WARDS(6),
    GUIDANCE(0),
    GUIDING_BOLT(1),
    GUST_OF_WIND(EVOCATION, 2, "1 action", "self", "60' line", "V,S,M", "up to 1 minute",
        "create a strong wind. Creatures in wind Str. save each turn or be push 15' away."),
    HAIL_OF_THORNS(1),
    HALLOW(5),
    HALLUCINATORY_TERRAIN(4),
    HARM(6),
    HASTE(3),
    HEAL(6),
    HEALING_WORD(1),
    HEAT_METAL(2),
    HELLISH_REBUKE(EVOCATION, 1, "1 reaction", "60'", "1 creature", "V,S", "-",
        "2d10 fire damage Dex. save for half (+1d10 / lev)"),
    HEROES_FEAST(6),
    HEROISM(1),
    HEX(1),
    HOLD_MONSTER(5),
    HOLD_PERSON(2),
    HOLY_AURA(8),
    HUNGER_OF_HADAR(3),
    HUNTERS_MARK(1),
    HYPNOTIC_PATTERN(3),
    ICE_STORM(EVOCATION, 4, "1 action", "300'", "20' radius", "V,S,M", "-",
        "2d8 bludgeon dam, 4d6 cold dam, save vs Dex half"),
    IDENTIFY(MagicSchool.DIVINATION, 1, "1 minute", "touch", "1 object", "V,S,M (100gp)", "I",
        "identify magic"),
    ILLUSORY_SCRIPT(1),
    IMPRISONMENT(9),
    INCENDIARY_CLOUD(8),
    INFLICT_WOUNDS(1),
    INSECT_PLAGUE(5),
    INVISIBILITY(2),
    JUMP(1),
    KNOCK(2),
    LEGEND_LORE(MagicSchool.DIVINATION, 5, "10 minutes", "self", "-", "V,S,M (450GP)", "-",
        "learn lore for person, place or object"),
    LEOMUNDS_SECRET_CHEST(4),
    LEOMUNDS_TINY_HUT(3),
    LESSER_RESTORATION(2),
    LEVITATE(2),
    LIGHT(EVOCATION, 0, "1 ation", "touch", "1 object", "V,M", "1 hour",
        "light 40' radius"),
    LIGHTNING_ARROW(3),
    LIGHTNING_BOLT(3),
    LOCATE_ANIMALS_OR_PLANTS(2),
    LOCATE_CREATURE(4),
    LOCATE_OBJECT(2),
    LONGSTRIDER(1),
    MAGE_ARMOR(ABJURATION, 1, "1 action", "touch", "1 creature", "V,S,M", "8 hours",
        "AC 13 + Dex bonus"),
    MAGE_HAND(CONJURATION, 0, "1 action", "30'", "-", "V,S", "1 minute",
        "spectral hand"),
    MAGIC_CIRCLE(3),
    MAGIC_JAR(6),
    MAGIC_MISSILE(EVOCATION, 1, "1 action", "120'", "3 darts + 1 / level", "V,S", "-",
        "1d4+1 damage"),
    MAGIC_MOUTH(2),
    MAGIC_WEAPON(TRANSMUTATION, 2, "1 bonus action", "touch", "1 weapon", "V,S", "up to 1 hour",
        "+1 damage / attack (lev 4: +2, lev 6: +3)"),
    MAJOR_IMAGE(ILLUSION, 3, "1 action", "120'", "20' cube", "V,S,M", "up to 10 minutes (lev 6: perm)",
        "create illusion"),
    MASS_CURE_WOUNDS(EVOCATION, 5, "1 action", "60'", "up to 6 creature, 30' radius", "V,S", "-",
        "3d8 + spell ability heal (+1d8 / lev)"),
    MASS_HEAL(EVOCATION, 9, "1 action", "60'", "any number of creatures", "V,S", "-",
        "700 HP total healing"),
    MASS_HEALING_WORD(EVOCATION, 3, "1 bonus action", "60'", "up to 6 creatures", "V", "-",
        "1d4 + spell ability heal (+1d4 / lev)"),
    MASS_SUGGESTION(6),
    MAZE(8),
    MELD_INTO_STONE(3),
    MELFS_ACID_ARROW(2),
    MENDING(0),
    MESSAGE(0),
    METEOR_SWARM(9),
    MIND_BLANK(8),
    MINOR_ILLUSION(0),
    MIRAGE_ARCANE(7),
    MIRROR_IMAGE(2),
    MISLEAD(2),
    MISTY_STEP(2),
    MODIFY_MEMORY(5),
    MOONBEAM(2),
    MORDENKAINENS_FAITHFUL_HOUND(4),
    MORDENKAINENS_MAGNIFICENT_MANSION(7),
    MORDENKAINENS_PRIVATE_SANCTUM(4),
    MORDENKAINENS_SWORD(7),
    MOVE_EARTH(6),
    NONDETECTION(ABJURATION, 3, "1 action", "touch", "1 creature, place or object", "V,S,M (25GP)",
        "8 hours", "hide from magical detection"),
    NYSTULS_MAGIC_AURA(2),
    OTILUKES_FREEZING_SPHERE(6),
    OTILUKES_RESILIENT_SPHERE(4),
    OTTOS_IRRESISTIBLE_DANCE(6),
    PASS_WITHOUT_TRACE(ABJURATION, 2, "1 action", "self", "all creatures within 30'", "V,S,M",
        "up to 1 hour", "+10 bonus to Stealth checks"),
    PASSWALL(5),
    PHANTASMAL_FORCE(2),
    PHANTASMAL_KILLER(4),
    PHANTOM_STEED(3),
    PLANAR_ALLY(6),
    PLANAR_BINDING(5),
    PLANE_SHIFT(7),
    PLANT_GROWTH(3),
    POISON_SPRAY(CONJURATION, 0, "1 action", "10'", "1 creature", "V,S", "-",
        "[($level+7)/6]d12 dam"),
    POLYMORPH(4),
    POWER_WORD_HEAL(9),
    POWER_WORD_KILL(9),
    POWER_WORD_STUN(8),
    PRAYER_OF_HEALING(2),
    PRESTIDIGITATION(0),
    PRISMATIC_SPRAY(7),
    PRISMATIC_WALL(9),
    PRODUCE_FLAME(0),
    PROGRAMMED_ILLUSION(6),
    PROJECT_IMAGE(7),
    PROTECTION_FROM_ENERGY(3),
    PROTECTION_FROM_EVIL_AND_GOOD(1),
    PROTECTION_FROM_POISON(2),
    PURIFY_FOOD_AND_DRINK(1),
    RAISE_DEAD(5),
    RARYS_TELEPATHIC_BOND(5),
    RAY_OF_ENFEEBLEMENT(2),
    RAY_OF_FROST(EVOCATION, 0, "1 action", "60'", "1 creature", "V,S", "-",
        "[($level+7)/6]d8 cold damage"),
    RAY_OF_SICKNESS(1),
    REGENERATE(7),
    REINCARNATE(5),
    REMOVE_CURSE(3),
    RESISTANCE(0),
    RESURRECTION(7),
    REVERSE_GRAVITY(7),
    REVIVIFY(3),
    ROPE_TRICK(2),
    SACRED_FLAME(0),
    SANCTUARY(1),
    SCORCHING_RAY(2),
    SCRYING(MagicSchool.DIVINATION, 5, "10 minutes", "self", "1 creature", "V,S,M", "up to 10 minutes",
        "Can see and hear creature; Wis. save"),
    SEARING_SMITE(1),
    SEE_INVISIBILITY(2),
    SEEMING(5),
    SENDING(3),
    SEQUESTER(7),
    SHAPECHANGE(9),
    SHATTER(2),
    SHIELD(ABJURATION, 1, "reaction", "Self", "-", "V,S", "1 round",
        "AC +5"),
    SHIELD_OF_FAITH(1),
    SHILLELAGH(0),
    SHOCKING_GRASP(0),
    SILENCE(2),
    SILENT_IMAGE(ILLUSION, 1, "1 action", "60'", "1 object", "V,S,M", "up to 10 minutes",
        "visual illusion"),
    SIMULACRUM(7),
    SLEEP(1),
    SLEET_STORM(3),
    SLOW(3),
    SPARE_THE_DYING(0),
    SPEAK_WITH_ANIMALS(MagicSchool.DIVINATION, 1, "1 action", "self", "-", "V,S", "10 minutes",
        "communicate with beasts"),
    SPEAK_WITH_DEAD(3),
    SPEAK_WITH_PLANTS(3),
    SPIDER_CLIMB(2),
    SPIKE_GROWTH(2),
    SPIRIT_GUARDIANS(3),
    SPIRITUAL_WEAPON(2),
    STAGGERING_SMITE(4),
    STINKING_CLOUD(3),
    STONE_SHAPE(4),
    STONESKIN(4),
    STORM_OF_VENGEANCE(9),
    SUGGESTION(2),
    SUNBEAM(6),
    SUNBURST(8),
    SWIFT_QUIVER(5),
    SYMBOL(7),
    TASHAS_HIDEOUS_LAGHTER(1),
    TELEKINESIS(5),
    TELEPATHY(8),
    TELEPORT(7),
    TELEPORTATION_CIRCLE(5),
    TENSERS_FLOATING_DISK(1),
    THAUMATURGY(0),
    THORN_WHIP(0),
    THUNDEROUS_SMITE(1),
    THUNDERWAVE(1),
    TIME_STOP(9),
    TONGUES(3),
    TRANSPORT_VIA_PLANTS(6),
    TREE_STRIDE(5),
    TRUE_POLYMORPH(9),
    TRUE_RESURRECTION(9),
    TRUE_SEEING(6),
    TRUE_STRIKE(0),
    TSUNAMI(8),
    UNSEEN_SERVANT(1),
    VAMPIRIC_TOUCH(3),
    VICIOUS_MOCKERY(0),
    WALL_OF_FIRE(4),
    WALL_OF_FORCE(5),
    WALL_OF_ICE(6),
    WALL_OF_STONE(5),
    WALL_OF_THORNS(6),
    WARDING_BOND(ABJURATION, 2, "1 action", "touch", "1 creature", "V,S,M", "1 hour",
        "+1 AC, saving throws; resistance to damage."),
    WATER_BREATHING(3),
    WATER_WALK(3),
    WEB(CONJURATION, 2, "1 action", "60'", "20' cube", "V,S,M", "up to 1 hour",
        "creatures in web constrained unless save vs Dex."),
    WEIRD(9),
    WIND_WALK(6),
    WIND_WALL(3),
    WISH(9),
    WITCH_BOLT(1),
    WORD_OF_RECALL(6),
    WRATHFUL_SMITE(1),
    ZONE_OF_TRUTH(2);

    private final MagicSchool school;
    private final int level;
    private final String castingTime;
    private final String range;
    private final String area;
    private final String duration;
    private final String components;
    private final String effect;

    private Spell(MagicSchool school, int level, String castingTime,
        String range, String area, String components, String duration,
        String effect) {
        this.school = school;
        this.level = level;
        this.castingTime = castingTime;
        this.range = range;
        this.area = area;
        this.duration = duration;
        this.components = components;
        this.effect = effect;
    }

    private Spell(int level, CharacterClass... classes) {
        this.school = ABJURATION;
        this.level = level;
        this.castingTime = "I";
        this.range = "0";
        this.area = "0";
        this.duration = "1";
        this.components = "VSM";
        this.effect = "Effect";
    }

    @Override
    public AttributeType getType() {
        return AttributeType.SPELL;
    }

    public int getLevel() {
        return level;
    }

    public String getEffect(Character character) {
        return StringUtils.expand(effect, character);
    }

    public String getArea() {
        return area;
    }

    public String getDuration() {
        return duration;
    }

    public String getCastingTime() {
        return castingTime;
    }

    public String getRange() {
        return range;
    }

    public String getComponents() {
        return components;
    }

    public String toString() {
        return StringUtils.capitaliseEnumName(name());
    }

    @Override
    public Stream<String> getDescription(Character character) {
        return Stream.of(
            school.toString() + " level " + level,
            "casting time " + castingTime,
            "range " + range,
            "area of effect " + area,
            "duration " + duration,
            "effect " + getEffect(character));
    }

    public static Spell load(Node node) {
        return Spell.valueOf(node.getTextContent());
    }
}
